#!/usr/bin/env python3

import httpx as requests
import subprocess
import sys

URL = "https://dolarapi.com/v1/dolares"

def get_width(items) -> int:
    item_len = [len(str(item)) for item in items]
    return max(item_len)

def get_message(data: dict) -> str:
    max_label_width = get_width(data.keys()) + 2  # Adding extra space for padding
    max_value_width = get_width(data.values()) + 2  # Adding extra space for padding
    result = [f"{label.center(max_label_width)}: {('$' + str(value)).center(max_value_width)}" for label, value in data.items()]
    return "\n".join(result)

def main() -> None:
    json = requests.get(URL).json()
    print(json)

    blue, oficial = json[0]['venta'], json[1]['venta']

    argument = sys.argv[1:]
    if not argument:
        msg = get_message({
            "blue": blue,
            "oficial": oficial,
        })
    else:
        crypto_buy = json[5]['compra']*0.97
        msg = get_message({
            "blue": crypto_buy,
            "pesos": int(argument[0])*crypto_buy
        })

    subprocess.Popen(f"notify-send '{msg}'", shell=True)

if __name__ == "__main__":
    main()

