#!/usr/bin/env fish
# Initialize variables
set reverse false
# Parse options
for arg in $argv
    switch $arg
        case '-r'
            set reverse true
    end
end
# Check if a destination argument is provided
if test (count $argv) -eq 0
    echo "Usage: cmd [-r] <destination>"
    exit 1
end
# The last argument is the destination
set path $argv[-1]
set path (realpath $path)/
# Set source and destination based on the reverse flag
if test $reverse = true
    set source "192.168.1.7:$path"
    set destination "$path"
else
    set source "$path"
    set destination "192.168.1.7:$path"
end
# Run rsync
echo "Sending from $source to $destination"
rsync -iPa -v --ignore-existing --exclude={'__pycache__', 'node_modules', 'custom-distros/work', "*.mp4", "venv*", ".mypy_cache"} "$source" "$destination"

