#!/sbin/sh

breaknum=1
workset=25
break_duration=5
speak_interval=5

function notify() {
    dunstify "$1"
  ( speaker-test -t sine -f 1000  > /dev/null 2>&1 )& pid=$! ; sleep 0.5s ; kill -9 $pid > /dev/null 2>&1
}

function work(){
  local total=$1
  for ((mins=$((total-speak_interval)); mins > 0; mins=$((mins-speak_interval)))); do
    sleep "$((mins*60))" && notify "$speak_interval minutes have passed" &
  done
  timer "$1m" "Work"
  timer "$((break_duration))m" "Break #$breaknum"
  breaknum=$((breaknum+1))
}

for ((a=1; a <= $1; a++)); do
  work $workset
done

