#!/bin/sh

project=$(cat ~/.config/scripts/.projects | fzf)
name=$2
breaknum=1

function work(){
  local total=$1
  for ((mins=$((total-5)); mins > 0; mins=$((mins-5)))); do
    sleep "$((mins*60))" && espeak "$((total-mins)) minutes left" &
  done
  toggl start -o $project $name
  timer "$1m" "Work"
  toggl stop
  espeak "Take a break"
  timer "$((30-total))m" "Break $breaknum"
  breaknum=$((breaknum+1))
}

for ((a=1; a <= $1; a++)); do
  test $a -eq 1 && espeak "Start working" || espeak "Start another task"
  work 25

  if [[ $((breaknum%4)) -eq 0 ]]; then
    espeak "Make corrections"
    work 15
  else
    espeak "Start another task"
    work 25
  fi
done

