#!/bin/sh

function work(){
  local total=$1
  for ((mins=$((total-5)); mins > 0; mins=$((mins-5)))); do
    sleep "$((mins*60))" && espeak "$((total-mins)) minutes left" &
  done
  timer "$1m" "Work"
}

#project=$(cat ~/.config/scripts/.projects | fzf)
#toggl start -o $project $2

for ((a=1; a <= $1; a++)); do
  espeak "Start working"
  work 25
  espeak "Take a break" & timer 5m "Break $((a+(a+1)%2))"

  if [[ $((a%2)) -eq 0 ]]; then
    espeak "Make corrections"
    work 15
    espeak "Take a break" & timer 15m "Break $((a+(a+1)%2+1))"
  else
    espeak "Start another task"
    work 25
    espeak "Take a break" & timer 5m "Break $((a+(a+1)%2+1))"
  fi

done

