#!/bin/sh

#project=$(cat ~/.config/scripts/.projects | sed -r 's/(^\s|\s+$)//g' | dmenu -i)
#description=$(echo "" | dmenu -p 'Task Description: ' -i)
#toggl start -o "$project" "$description"
#tstatus
