#!/bin/sh

project=$(cat ~/.config/scripts/.projects | sed -r 's/(^\s|\s+$)//g' | dmenu) # Using xargs to trim string
description=$(echo "" | dmenu -p 'Task Description:') 

toggl start -o "$project" "$description"
tstatus
