#!/bin/sh
WS_ID=mp-ws
PROJECT_FILE=~/.config/scripts/.mp-projects

configure_workspace() {
  toggl config workspace "$WS_ID"
}

get_project() {
  cat "$PROJECT_FILE" | sed -r 's/(^\s|\s+$)//g' | dmenu -i
}

configure_workspace
update_project_list() {
  toggl projects ls -f name | sed '1d' > "$PROJECT_FILE"
}

update_project_list

project=$(get_project)

today=$(date +"%Y-%m-%dT%H:%M:%S")
one_month_ago=$(date -d "1 month ago" +"%Y-%m-%dT%H:%M:%S")

detail=$(toggl ls -o $project -s "$one_month_ago")
total=$(toggl sum -o $project -st -s "$one_month_ago" -p "$today" | grep "total" | awk '{print $2}')
echo -e "$total\n$detail" | xclip -selection clipboard
dunstify -t 15000 "Copied work summary to clipboard"
